#!/usr/bin/env bash
#SBATCH -A NAISS2024-5-119 -p alvis
#SBATCH -N 1 --gpus-per-node=A40:1
#SBATCH -t 0-01:00:00

module load  PyTorch/2.1.2-foss-2023a-CUDA-12.1.1
module load scikit-learn/1.3.1-gfbf-2023a
module load matplotlib/3.7.2-gfbf-2023a
module load  PyTorch-Lightning/2.2.1-foss-2023a-CUDA-12.1.1
module load h5py/3.9.0-foss-2023a
module load PyTorch-bundle/2.1.2-foss-2023a-CUDA-12.1.1

echo "begin generate"
python train.py